version: '3.8'

services:
  todo-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - todo-data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped

volumes:
  todo-data: