name: Node.js CI

on:
  push:
    branches: [ main, todo-app-feature ]
  pull_request:
    branches: [ main, todo-app-feature ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Run security audit
      run: npm audit --audit-level=moderate
      
  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: docker-compose build --no-cache
      
    - name: Test Docker container
      run: |
        docker-compose up -d
        sleep 15
        # Test HTTP endpoint accessibility
        curl -f http://localhost:3000 || exit 1
        docker-compose down
